/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomConnectionLine: typeof import('./components/CustomConnectionLine.vue')['default']
    CustomEdge: typeof import('./components/CustomEdge.vue')['default']
    CustomMaker: typeof import('./components/CustomMaker.vue')['default']
    CustomMarker: typeof import('./components/CustomMarker.vue')['default']
    CustomNode: typeof import('./components/CustomNode.vue')['default']
    DropzoneBackground: typeof import('./components/DropzoneBackground.vue')['default']
    GraphLogo: typeof import('./components/GraphLogo.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./components/SettingsPanel.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
  }
}
