/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DropzoneBackground: typeof import('./components/DropzoneBackground.vue')['default']
    GraphLogo: typeof import('./components/GraphLogo.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
  }
}
